server:
  port: 8001


#应用名称
spring:
  application:
    name: dcloud-account

#服务注册发现
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.44.128:8848
        username: nacos
        password: nacos

#数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.44.128:3306/short-link?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 'Root_123456'



#配置plus打印sql日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

